---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"

xpack.security.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false

elasticsearch.url: http://elasticsearch:9200
